version: "2"
services:
  fabvision-app:
    image: rosariohg/fabvision-app
    command: node app.js
    ports:
     - "80:4000"
  fabvision-tf:
    image: rosariohg/fabvision-tf
    command: python app.py
    ports:
     - "5000:5000"
    #volumes:
    #- .:/code